### ISSUE TITLE
Can Sidekiq/ActiveJob agent reuse config from application.rb?

### ISSUE THREAD

**Issue by machty** [jgraichen/telegraf-ruby#12]
I have `config.telegraf.connect = "udp://localhost:61022"` in my config/application.rb; is there any way to just the Sidekiq middleware use the same agent configuration from config/application.rb? If not, I have to copy the `"udp://localhost:61022"` everywhere else, which seems weird, but maybe I'm thinking about it wrong.

**Comment by jgraichen** [comment]
An [initializer creates a telegraf agent](https://github.com/jgraichen/telegraf-ruby/blob/master/lib/telegraf/railtie.rb#L72) and stores it in `app.config.telegraf.agent`. This agent is used when installing the sidekiq middleware in [another initializer](https://github.com/jgraichen/telegraf-ruby/blob/master/lib/telegraf/railtie.rb#L124).

Are you doing some manual install? The sidekiq middleware should be automatically installed if used inside in a Rails application.

**Comment by jgraichen** [comment]
In a Rails application, it should be enough to add the `require` statements to `config/application.rb`:

```ruby
# ...

require 'telegraf/rails'

module MyApp
  class Application < Rails::Application
    # ...
```

**Comment by machty** [comment]
Oh, no I'm using Rails. I misread the docs and figured I still needed to do the Sidekiq chain config.

**Comment by machty** [comment]
Yeah it worked, just was surprised that my "background" metric was renamed to "sidekiq", so I made this PR: #13.

Man, if people know what's good for them I'd expect this repo to have 400 stars by July.
