### ISSUE TITLE
Influxdb 2.0?

### ISSUE THREAD

**Issue by bszerdy** [jgraichen/telegraf-ruby#16]
Should this gem work with influxdb 2.0? I can't find any information in the readme that addresses this question.

**Comment by franzliedke** [comment]
Judging by the [README of the `influxdb` gem we're using](https://github.com/influxdata/influxdb-ruby), it likely does not work. The [new client gem](https://github.com/influxdata/influxdb-client-ruby) supports InfluxDB 2.0 and also 1.8+ - maybe it's time to release a new major that requires InfluxDB 1.8?

Then again, the only usage of code from the `influxdb` gem is this line:
https://github.com/jgraichen/telegraf-ruby/blob/7803b4aa56cf8989efdeed30c92cebce537e4334/lib/telegraf/agent.rb#L40

That feels like it's easy to make this library compatible with either client (or even *require* both 🤔) - would you be interested in sending a PR?

**Comment by franzliedke** [comment]
> or even *require* both

Both seem to have no further gem dependencies - with standalone gems like that, the risk of version conflicts seems pretty low, so requiring both would be my personal favorite. Choosing one or the other would then be a config option of our `Agent` class.

**Comment by jgraichen** [comment]
This gem does not write to InfluxDB 1.0 nor 2.0, it only sends data _in the Influx line protocol format_ to a [telegraf socket_listener](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/socket_listener). Telegraf does [support InfluxDB 2.0](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/influxdb_v2).

This gem explicitly does not support direct submitting points to InfluxDB. We do not want to handle retries, queuing points, unreliable networks, server restarts etc. All of that can be better handled by a local telegraf agent.

I explicitly recommend this client only for sending data to a telegraf agent on the same host (usually localhost).

**Comment by jgraichen** [comment]
The `influxdb` gem really is only used for line protocol serialization.
