### ISSUE TITLE
Exclude paths (e.g. health checks)

### ISSUE THREAD

**Issue by leshik** [jgraichen/telegraf-ruby#24]
Can we somehow exclude paths, e.g. health checks? I tried monkey patching the `telegraf.instrumentation` middleware, but it goes through the `telegraf.rack` anyway.

**Comment by jgraichen** [comment]
With v3.0.0, you can register custom `before_send` hooks to filter or manipulate data points before they are emitted (see #27).

Please note that I do not recommend dropping metric points as this will screw all your derived metrics e.g. percentiles won't be valid anymore, total request counts will be offsetted, and issues with the excluded routes cannot be observed anymore. All your webservers would appear idle even when they are stuck in/overloaded with these routes.
